version: '3.3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=payment_backoffice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kamisama123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    container_name: milio_dv_back_container

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  redis:
    volumes:
      - ./redis-persistence:/bitnami/redis/data
    image: 'redis'
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
    ports:
        - 6379:6379
    container_name: redis_container

